"""populates  Pedido

Revision ID: 0a5d7cb2bcb3
Revises: ffdb8fce8ac4
Create Date: 2023-08-21 15:26:37.914724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5d7cb2bcb3'
down_revision: Union[str, None] = 'ffdb8fce8ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
