"""concertando Pedido

Revision ID: feb4129644dc
Revises: 93ed7286b4d3
Create Date: 2023-08-21 15:17:39.347161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb4129644dc'
down_revision: Union[str, None] = '93ed7286b4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('tipo_tipo_entrega', sa.String(), nullable=True))
    op.drop_column('pedido', 'tipo_endereco')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('tipo_endereco', sa.VARCHAR(), nullable=True))
    op.drop_column('pedido', 'tipo_tipo_entrega')
    # ### end Alembic commands ###
