"""concertando Pedido

Revision ID: ffdb8fce8ac4
Revises: feb4129644dc
Create Date: 2023-08-21 15:19:02.458398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdb8fce8ac4'
down_revision: Union[str, None] = 'feb4129644dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('tipo_entrega', sa.String(), nullable=True))
    op.drop_column('pedido', 'tipo_tipo_entrega')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('tipo_tipo_entrega', sa.VARCHAR(), nullable=True))
    op.drop_column('pedido', 'tipo_entrega')
    # ### end Alembic commands ###
